### ISSUE TITLE
Module not found: Error: Can't resolve './live' in '/node_modules/chain-gun/edge'

### ISSUE THREAD

**Issue by rechl** [kristianmandrup/chaingun#2]
Hi, 
i try to use chain-gun with typescript/angular4. 

It seems a module named 'live.js' is missing. 
Could not find it in src folder/edge folder

```
ERROR in ./~/chain-gun/edge/all.js
Module not found: Error: Can't resolve './live' in 'xxxxxx/node_modules/chain-gun/edge'
 @ ./~/chain-gun/edge/all.js 23:12-29
 @ ./~/chain-gun/edge/index.js

```
any ideas?

**Comment by kristianmandrup** [comment]
Please fork the repo, debug and send a PR. I'm no longer maintaining `chain-gun`. Sorry.
